### ISSUE TITLE
Reference to undefined variable gBrowser

### ISSUE THREAD

**Issue by dirkf** [Lootyhoof/stylem#7]
At start-up and possibly other times the identifier gBrowser used in this line may not be defined:

https://github.com/Lootyhoof/stylem/blob/2708543314904806f3d30e1411f55bd90441adfc/src/content/overlay.js#L536 

```Javascript
	get currentURI() {
/*536*/		return gBrowser.currentURI; 
	},
```
This probably happens/ed in Stylish and Stylus as well.

As there seem to be no ill effects except an Error Console entry, instead try:
```Javascript
	get currentURI() {
		return (typeof gBrowser != "undefined") ? gBrowser.currentURI: null; 
	},
```

**Comment by Lootyhoof** [comment]
Sorry for the delay. Thanks for spotting this!

**Comment by dirkf** [comment]
On 01/12/19 14:13, Ryan C wrote:
> Sorry for the delay. Thanks for spotting this!

Thanks, glad to help in the war against bad web designers.

/df

--
London SW6
UK
